# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14QUIkuTC0ZHLpajV4yoL3rylczwOmnGV
"""

import streamlit as st
import pickle
import numpy as np

# Load the trained model
with open('logistic_model.pkl', 'rb') as file:
    model = pickle.load(file)

st.title("Logistic Regression Prediction App")


# Input fields (example features, modify according to your model's input)
feature1 = st.number_input("Enter value for Feature 1")
feature2 = st.number_input("Enter value for Feature 2")

# Predict button
if st.button("Predict"):
    input_data = np.array([[feature1, feature2]])
    prediction = model.predict(input_data)
    st.write(f"Prediction: {prediction[0]}")